[package]
name    = "ncollide_entities"
version = "0.2.0"
authors = [ "Sébastien Crozet <developer@crozet.re>" ]

description = "2 and 3-dimensional collision detection library in Rust: module describing the geometric entities and their mathematical definitions."
documentation = "http://ncollide.org/doc/ncollide"
homepage = "http://ncollide.org"
repository = "https://github.com/sebcrozet/ncollide"
keywords = [ "collision", "geometry", "distance", "ray", "convex" ]
license = "BSD-3-Clause"

[lib]
name = "ncollide_entities"
path = "lib.rs"

[dependencies]
rustc-serialize = "*"
num = "*"
nalgebra = "*"
#ncollide_math = "*"
#ncollide_utils = "*"


# Just for demo link purpose!

[dependencies.ncollide_math]
path = "../ncollide_math"

[dependencies.ncollide_utils]
path = "../ncollide_utils"
